# Generated by Django 3.0.8 on 2020-07-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='account/img/user_profile_image/user_default_image.png', upload_to='account/user_profile_image/', verbose_name='대표 이미지'),
        ),
    ]
