# Generated by Django 3.0.8 on 2020-07-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_Customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_Stationer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_WebSeller',
        ),
    ]
