# Generated by Django 3.0.8 on 2020-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rawLocation',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='문방구/리뷰어 도로명 주소'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='문방구/리뷰어 위치 위도'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='문방구/리뷰어 위치 경도'),
        ),
    ]
