# Generated by Django 3.0.8 on 2020-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200727_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_Customer',
            field=models.BooleanField(default=False, verbose_name='customer status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_Stationer',
            field=models.BooleanField(default=False, verbose_name='stationer status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_WebSeller',
            field=models.BooleanField(default=False, verbose_name='webSeller status'),
        ),
    ]
