# Generated by Django 3.0.8 on 2020-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200728_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(choices=[('10s', '10'), ('20s', '20'), ('30s', '30'), ('40s', '40'), ('50s', '50'), ('60s', '60'), ('etcs', '기타')], default=('etcs', '기타'), max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(choices=[('J1', '학생'), ('J2', '직장인'), ('J3', '사업가'), ('J4', '기타')], default=('J4', '기타'), max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='usage',
            field=models.CharField(choices=[('U1', '그림그리기'), ('U2', '문서작성'), ('U3', '다이어리 꾸미기'), ('U4', '필기(공부 혹은 시험)'), ('U5', '기타')], default=('U5', '기타'), max_length=20),
        ),
    ]
