# Generated by Django 3.0.8 on 2020-07-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200724_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationer',
            options={'verbose_name': 'WebSeller', 'verbose_name_plural': 'WebSeller'},
        ),
        migrations.AlterModelOptions(
            name='webseller',
            options={'verbose_name': 'WebSeller', 'verbose_name_plural': 'WebSeller'},
        ),
    ]
