# Generated by Django 3.0.8 on 2020-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200803_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rawLocation',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='문방구/리뷰어 좌표'),
        ),
    ]
