# Generated by Django 3.0.8 on 2020-08-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200803_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rawLocation',
        ),
    ]
