# Generated by Django 3.0.8 on 2020-07-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200724_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationer',
            options={'verbose_name': 'Stationer', 'verbose_name_plural': 'Stationer'},
        ),
    ]
