# Generated by Django 3.0.8 on 2020-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200730_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='account/profile_image/user_default_image.png', null=True, upload_to='account/profile_image', verbose_name='대표 이미지'),
        ),
    ]
