# Generated by Django 3.1 on 2020-08-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200826_1706'),
        ('account', '0004_auto_20200826_1433'),
    ]

    operations = [
    ]
