# Generated by Django 3.0.8 on 2020-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200827_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(choices=[('J0', '기타'), ('J1', '학생'), ('J2', '아티스트'), ('J3', '자영업'), ('J4', '무직')], default=('J0', '기타'), max_length=10, null=True, verbose_name='직업'),
        ),
    ]
