# Generated by Django 3.0.8 on 2020-07-27 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='상품 이름')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='제조사')),
                ('description', models.TextField(verbose_name='제조사')),
                ('likers', models.ManyToManyField(related_name='productLikers', to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
            ],
        ),
    ]
