# Generated by Django 3.0.8 on 2020-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20200805_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='modified',
            field=models.BooleanField(default=False, verbose_name='수정'),
        ),
    ]
