# Generated by Django 3.0.8 on 2020-08-27 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_auto_20200826_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationersellinfo',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StationerSellInfoSeller', to=settings.AUTH_USER_MODEL, verbose_name='문방구 판매자'),
        ),
        migrations.AlterField(
            model_name='websellinfo',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webSellInfoSeller', to=settings.AUTH_USER_MODEL, verbose_name='웹 판매자'),
        ),
    ]
