# Generated by Django 3.0.8 on 2020-08-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200813_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penreview',
            name='versatility',
        ),
    ]
