# Generated by Django 3.0.8 on 2020-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_review_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='mainApp.ProductTag'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.CharField(max_length=15, unique=True, verbose_name='상품 태그'),
        ),
    ]
