# Generated by Django 3.0.8 on 2020-08-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20200806_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tag_set',
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='mainApp.Review', verbose_name='가리키는 상품'),
        ),
        migrations.AddField(
            model_name='review',
            name='rawTagString',
            field=models.TextField(blank=True, default='', verbose_name='제품 태그 목록 원본 데이터'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainApp.ProductTag'),
        ),
    ]
