# Generated by Django 3.0.8 on 2020-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20200806_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15, unique=True, verbose_name='상품 태그')),
                ('targetReview', models.ManyToManyField(blank=True, null=True, to='mainApp.Review', verbose_name='가리키는 상품')),
            ],
            options={
                'verbose_name': '리뷰 태그',
            },
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainApp.ReviewTag'),
        ),
    ]
