# Generated by Django 3.0.8 on 2020-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20200806_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtag',
            name='tag',
            field=models.CharField(max_length=15, verbose_name='상품 태그'),
        ),
    ]
