# Generated by Django 3.0.8 on 2020-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20200806_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtag',
            name='targetReview',
            field=models.ManyToManyField(blank=True, to='mainApp.Review', verbose_name='가리키는 상품'),
        ),
    ]
