# Generated by Django 3.0.8 on 2020-08-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20200806_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=50, verbose_name='한줄평'),
        ),
    ]
