# Generated by Django 3.0.8 on 2020-08-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0009_review_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='리뷰 작성(수정)일')),
                ('body', models.TextField(verbose_name='댓글 내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to=settings.AUTH_USER_MODEL, verbose_name='리뷰 작성자')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentTargetReview', to='mainApp.Review', verbose_name='대상 리뷰')),
            ],
        ),
    ]
